#COMMENT
# Utilizar una imagen base de Python 3.10
FROM python:3.10

# Establecer variables de entorno para Python
ENV PYTHONUNBUFFERED=1
ENV API_BASE_URL=http://localhost:30632
# Crear y establecer el directorio de trabajo en el contenedor
WORKDIR /app
RUN mkdir -p /tmp/django_sessions
# Copiar el archivo de requisitos e instalar las dependencias
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código fuente del proyecto al contenedor
COPY IntegraSoft_Front /app/IntegraSoft_Front

# Cambiar el directorio de trabajo
WORKDIR /app/IntegraSoft_Front

# Ejecutar collectstatic
RUN python manage.py collectstatic --noinput
RUN chmod 777 /tmp/django_sessions
# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 8001

# Comando para ejecutar la aplicación
CMD ["gunicorn", "IntegraSoft_Front.wsgi:application", "--bind", "0.0.0.0:8001"]

