# Utilizar una imagen base de Nginx
FROM nginx:alpine

# Copiar la configuración de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiar los archivos estáticos
COPY ./IntegraSoft_Front/staticfiles /app/staticfiles

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 80
